@echo off
setlocal EnableDelayedExpansion

cd /d "%~dp0"

echo.
echo ================================================
echo   Phone Camera Setup for go2rtc
echo ================================================
echo.
echo Choose phone app/source type:
echo   1. Android IP Webcam RTSP (^/h264.sdp^)
echo   2. Enter custom RTSP URL

echo.
set /p mode="Enter choice (1-2): "
set "mode=%mode: =%"

if "%mode%"=="1" goto android_ipwebcam
if "%mode%"=="2" goto custom_url

echo Invalid choice.
pause
exit /b 1

:android_ipwebcam
echo.
set /p phone_ip="Enter phone IP address (example 192.168.1.3): "
set "phone_ip=%phone_ip: =%"
if "%phone_ip%"=="" (
  echo Phone IP is required.
  pause
  exit /b 1
)
set "phone_host=%phone_ip%"
set "phone_host=%phone_host:rtsp://=%"
for /f "tokens=1 delims=/" %%A in ("%phone_host%") do set "phone_host=%%A"
for /f "tokens=1 delims=:" %%A in ("%phone_host%") do set "phone_host=%%A"
set "source_url=rtsp://%phone_host%:8080/h264.sdp"
goto apply

:custom_url
echo.
set /p source_url="Enter full RTSP URL: "
if "%source_url%"=="" (
  echo RTSP URL is required.
  pause
  exit /b 1
)
goto apply

:apply
echo.
echo Using source URL:
echo   %source_url%

if exist "go2rtc.yaml" copy /y go2rtc.yaml go2rtc.yaml.bak >nul
if exist "config.py" copy /y config.py config.py.bak >nul

(
  echo # go2rtc local relay configuration for low-latency development
  echo # Auto-generated by setup_phone_camera.bat
  echo.
  echo api:
  echo   listen: ":1984"
  echo.
  echo rtsp:
  echo   listen: ":8554"
  echo.
  echo streams:
  echo   cam:
  echo     - %source_url%
) > go2rtc.yaml

powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0update_go2rtc_config.ps1" "%source_url%"
if errorlevel 1 goto config_update_failed

echo.
echo Setup complete.
echo   go2rtc source: %source_url%
echo   app relay URL: rtsp://127.0.0.1:8554/cam
echo.
echo Next steps:
echo   1. Start phone camera stream on your phone.
echo   2. Run start_go2rtc.bat
echo   3. Run python main.py

echo.
pause
exit /b 0

:config_update_failed
echo.
echo [ERROR] Failed to update config.py
echo Please open config.py and check GO2RTC_STREAM_NAME, GO2RTC_SOURCE_URL and RTSP_URL.
echo.
pause
exit /b 1
